server:
  port: 6868
eureka:
  client:
    register-with-eureka: false #不将自己注册给eruka
    fetch-registry: false #不从eureka中拉取数据
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/